backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /static

collections:
  - name: "wiki"
    label: "wiki"
    folder: "src/pages/wiki"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "wiki"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cover", name: image, widget: image, default: "/img/default.jpeg"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "posts"
    label: "posts"
    folder: "src/pages/posts"
    create: true
    editor:
     preview: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "posts"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cover", name: image, widget: image, default: "/img/default.jpeg"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
